In [55]:
# Importing essential libraries



In [56]:
# Loading the dataset
import pandas as pd
import numpy as np
from IPL import *

In [57]:
X_test=pd.read_csv('IPL1_test.csv')

In [58]:
X_test

match_id  season start_date                  venue  innings  ball  \
0     1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.1   
1     1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.2   
2     1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.3   
3     1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.4   
4     1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.5   
..        ...     ...        ...                    ...      ...   ...   
119   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1  19.3   
120   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1  19.4   
121   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1  19.5   
122   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1  19.6   
123   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1  19.7   

                    batting_team         bowling_team            striker  \
0    Royal Challengers Bangalore  Chennai Super Kings          Q de Kock   
1    Royal Challengers Bangalore  Chennai Super Kings          Q de Kock   
2    Royal Challengers Bangalore  Chennai Super Kings            V Kohli   
3    Royal Challengers Bangalore  Chennai Super Kings            V Kohli   
4    Royal Challengers Bangalore  Chennai Super Kings            V Kohli   
..                           ...                  ...                ...   
119  Royal Challengers Bangalore  Chennai Super Kings           UT Yadav   
120  Royal Challengers Bangalore  Chennai Super Kings           UT Yadav   
121  Royal Challengers Bangalore  Chennai Super Kings  Washington Sundar   
122  Royal Challengers Bangalore  Chennai Super Kings  Washington Sundar   
123  Royal Challengers Bangalore  Chennai Super Kings  Washington Sundar   

           non_striker  ... extras  wides  noballs  byes  legbyes  penalty  \
0              V Kohli  ...      0    NaN      NaN   NaN      NaN      NaN   
1              V Kohli  ...      0    NaN      NaN   NaN      NaN      NaN   
2            Q de Kock  ...      0    NaN      NaN   NaN      NaN      NaN   
3            Q de Kock  ...      0    NaN      NaN   NaN      NaN      NaN   
4            Q de Kock  ...      0    NaN      NaN   NaN      NaN      NaN   
..                 ...  ...    ...    ...      ...   ...      ...      ...   
119  Washington Sundar  ...      1    1.0      NaN   NaN      NaN      NaN   
120  Washington Sundar  ...      0    NaN      NaN   NaN      NaN      NaN   
121     Mohammed Siraj  ...      0    NaN      NaN   NaN      NaN      NaN   
122     Mohammed Siraj  ...      0    NaN      NaN   NaN      NaN      NaN   
123     Mohammed Siraj  ...      0    NaN      NaN   NaN      NaN      NaN   

     wicket_type  player_dismissed other_wicket_type other_player_dismissed  
0            NaN               NaN               NaN                    NaN  
1            NaN               NaN               NaN                    NaN  
2            NaN               NaN               NaN                    NaN  
3            NaN               NaN               NaN                    NaN  
4            NaN               NaN               NaN                    NaN  
..           ...               ...               ...                    ...  
119          NaN               NaN               NaN                    NaN  
120       caught          UT Yadav               NaN                    NaN  
121          NaN               NaN               NaN                    NaN  
122          NaN               NaN               NaN                    NaN  
123          NaN               NaN               NaN                    NaN  

[124 rows x 22 columns]

In [59]:
X_test = X_test[X_test['ball']<=6.0]

In [60]:
match_group_1st = X_test.groupby(["match_id"])
m1=match_group_1st["runs_off_bat"].sum()

In [61]:
m1

match_id
1136584    52
Name: runs_off_bat, dtype: int64

In [62]:
arr = []
ar1 = []
for i in m1.index:
        """for _ in df_1st[(df_1st['match_id']==i)] :"""
        x1=np.zeros(len(X_test[(X_test['match_id']==i)]),dtype=int)
        x1+=m1[i]
        arr.append(x1)


for i in arr:
    for j in i: 
        ar1.append(int(j)) 

In [63]:
X_test['runs_6_overs']=ar1

<ipython-input-63-ba63300fbf15>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['runs_6_overs']=ar1


In [64]:
X_test.head()

match_id  season start_date                  venue  innings  ball  \
0   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.1   
1   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.2   
2   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.3   
3   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.4   
4   1136584    2018  4/25/2018  M.Chinnaswamy Stadium        1   0.5   

                  batting_team         bowling_team    striker non_striker  \
0  Royal Challengers Bangalore  Chennai Super Kings  Q de Kock     V Kohli   
1  Royal Challengers Bangalore  Chennai Super Kings  Q de Kock     V Kohli   
2  Royal Challengers Bangalore  Chennai Super Kings    V Kohli   Q de Kock   
3  Royal Challengers Bangalore  Chennai Super Kings    V Kohli   Q de Kock   
4  Royal Challengers Bangalore  Chennai Super Kings    V Kohli   Q de Kock   

   ... wides  noballs  byes  legbyes  penalty  wicket_type  player_dismissed  \
0  ...   NaN      NaN   NaN      NaN      NaN          NaN               NaN   
1  ...   NaN      NaN   NaN      NaN      NaN          NaN               NaN   
2  ...   NaN      NaN   NaN      NaN      NaN          NaN               NaN   
3  ...   NaN      NaN   NaN      NaN      NaN          NaN               NaN   
4  ...   NaN      NaN   NaN      NaN      NaN          NaN               NaN   

   other_wicket_type other_player_dismissed runs_6_overs  
0                NaN                    NaN           52  
1                NaN                    NaN           52  
2                NaN                    NaN           52  
3                NaN                    NaN           52  
4                NaN                    NaN           52  

[5 rows x 23 columns]

In [65]:
columns_to_remove = ['start_date' ,'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty',
       'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed','season', 'start_date','striker', 'non_striker', 'bowler','runs_6_overs','match_id','ball','runs_off_bat','wickets_6_overs']
#X_test.drop(labels=columns_to_remove, axis=1, inplace=True)

In [66]:
X_test.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'runs_6_overs'],
      dtype='object')

In [67]:
match_group_1st = X_test.groupby(["match_id"])
m1=match_group_1st["player_dismissed"].count()

In [68]:
arr = []
ar1 = []
for i in m1.index:
        """for _ in df_1st[(df_1st['match_id']==i)] :"""
        x1=np.zeros(len(X_test[(X_test['match_id']==i)]),dtype=int)
        x1+=m1[i]
        arr.append(x1)


for i in arr:
    for j in i: 
        ar1.append(int(j)) 

In [69]:
X_test['wickets_6_overs']=ar1

<ipython-input-69-1bb35d2320ab>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['wickets_6_overs']=ar1


In [70]:
X_test.drop(labels=columns_to_remove,
            axis=1, inplace=True)

C:\Users\thepr\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [71]:
X_test.loc[0]

venue                 M.Chinnaswamy Stadium
innings                                   1
batting_team    Royal Challengers Bangalore
bowling_team            Chennai Super Kings
Name: 0, dtype: object

In [72]:
len(X_test)


36

In [73]:
batting_team = X_test['batting_team'][0]
bowling_team = X_test['bowling_team'][0]
venue = X_test['venue'][0]
innings = X_test['innings'][0]


In [74]:
X_test

venue  innings                 batting_team  \
0   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
1   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
2   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
3   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
4   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
5   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
6   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
7   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
8   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
9   M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
10  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
11  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
12  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
13  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
14  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
15  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
16  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
17  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
18  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
19  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
20  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
21  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
22  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
23  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
24  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
25  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
26  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
27  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
28  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
29  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
30  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
31  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
32  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
33  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
34  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   
35  M.Chinnaswamy Stadium        1  Royal Challengers Bangalore   

           bowling_team  
0   Chennai Super Kings  
1   Chennai Super Kings  
2   Chennai Super Kings  
3   Chennai Super Kings  
4   Chennai Super Kings  
5   Chennai Super Kings  
6   Chennai Super Kings  
7   Chennai Super Kings  
8   Chennai Super Kings  
9   Chennai Super Kings  
10  Chennai Super Kings  
11  Chennai Super Kings  
12  Chennai Super Kings  
13  Chennai Super Kings  
14  Chennai Super Kings  
15  Chennai Super Kings  
16  Chennai Super Kings  
17  Chennai Super Kings  
18  Chennai Super Kings  
19  Chennai Super Kings  
20  Chennai Super Kings  
21  Chennai Super Kings  
22  Chennai Super Kings  
23  Chennai Super Kings  
24  Chennai Super Kings  
25  Chennai Super Kings  
26  Chennai Super Kings  
27  Chennai Super Kings  
28  Chennai Super Kings  
29  Chennai Super Kings  
30  Chennai Super Kings  
31  Chennai Super Kings  
32  Chennai Super Kings  
33  Chennai Super Kings  
34  Chennai Super Kings  
35  Chennai Super Kings

In [75]:
    temp_array=[]


    if batting_team == 'Chennai Super Kings':
        temp_array = temp_array + [1, 0, 0, 0, 0, 0, 0, 0]
    elif batting_team == 'Delhi Daredevils':
        temp_array = temp_array + [0, 1, 0, 0, 0, 0, 0, 0]
    elif batting_team == 'Kings XI Punjab':
        temp_array = temp_array + [0, 0, 1, 0, 0, 0, 0, 0]
    elif batting_team == 'Kolkata Knight Riders':
        temp_array = temp_array + [0, 0, 0, 1, 0, 0, 0, 0]
    elif batting_team == 'Mumbai Indians':
        temp_array = temp_array + [0, 0, 0, 0, 1, 0, 0, 0]
    elif batting_team == 'Rajasthan Royals':
        temp_array = temp_array + [0, 0, 0, 0, 0, 1, 0, 0]
    elif batting_team == 'Royal Challengers Bangalore':
        temp_array = temp_array + [0, 0, 0, 0, 0, 0, 1, 0]
    elif batting_team == 'Sunrisers Hyderabad':
        temp_array = temp_array + [0, 0, 0, 0, 0, 0, 0, 1]

    
    if bowling_team == 'Chennai Super Kings':
        temp_array = temp_array + [1, 0, 0, 0, 0, 0, 0, 0]
    elif bowling_team == 'Delhi Daredevils':
        temp_array = temp_array + [0, 1, 0, 0, 0, 0, 0, 0]
    elif bowling_team == 'Kings XI Punjab':
        temp_array = temp_array + [0, 0, 1, 0, 0, 0, 0, 0]
    elif bowling_team == 'Kolkata Knight Riders':
        temp_array = temp_array + [0, 0, 0, 1, 0, 0, 0, 0]
    elif bowling_team == 'Mumbai Indians':
        temp_array = temp_array + [0, 0, 0, 0, 1, 0, 0, 0]
    elif bowling_team == 'Rajasthan Royals':
        temp_array = temp_array + [0, 0, 0, 0, 0, 1, 0, 0]
    elif bowling_team == 'Royal Challengers Bangalore':
        temp_array = temp_array + [0, 0, 0, 0, 0, 0, 1, 0]
    elif bowling_team == 'Sunrisers Hyderabad':
        temp_array = temp_array + [0, 0, 0, 0, 0, 0, 0, 1]

    
    if venue == 'Arun Jaitley Stadium':
        temp_array = temp_array + [1, 0, 0, 0, 0, 0]
    elif venue == 'Eden Gardens':
        temp_array = temp_array + [0, 1, 0, 0, 0, 0]
    elif venue == 'M.Chinnaswamy Stadium':
        temp_array = temp_array + [0, 0, 1, 0, 0, 0]
    elif venue == 'MA Chidambaram Stadium, Chepauk, Chennai':
        temp_array = temp_array + [0, 0, 0, 1, 0, 0]
    elif venue == 'Narendra Modi Stadium, Ahmedabad':
        temp_array = temp_array + [0, 0, 0, 0, 1, 0]
    elif venue == 'Wankhede Stadium':
        temp_array = temp_array + [0, 0, 0, 0, 0, 1]
        
    if innings == 1:
        temp_array = temp_array + [1, 0]
    elif innings == 2:
        temp_array = temp_array + [0, 1]

    
    """ball=X_test['ball'][n-1]
    runs_of_bat=X_test['runs_off_bat'][n-1]
    runs = X_test['runs_6_overs'][n-1]
    wickets = X_test['wickets_6_overs'][n-1]"""

    print(temp_array)
    data = np.array([temp_array])
    my_prediction = int(regressor.predict(data)[0])
    print(my_prediction)

[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0]
43


In [76]:
data.shape

(1, 24)

In [77]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [78]:
ridge=Ridge()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,50,60,70,80,90,100,200,300,400,500,600,700,800,900,1000,5000,10e+10]}
ridge_regressor=GridSearchCV(ridge,parameters,scoring='r2',cv=5)
ridge_regressor.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 35, 40, 50, 60, 70, 80, 90, 100, 200,
                                   300, 400, 500, 600, 700, 800, 900, 1000,
                                   5000, 100000000000.0]},
             scoring='r2')

In [79]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 100000000000.0}
-0.04788942150537636


In [80]:
ridge_regressor.predict(data)

array([43.56665647])

In [81]:
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV

In [82]:
lasso=SGDRegressor()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,50,60,70,80,90,100,200,300,400,500,600,700,800,900,1000,5000,10e+10]}
lasso_regressor=GridSearchCV(lasso,parameters,scoring='r2',cv=5)

lasso_regressor.fit(X_train,y_train)
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

{'alpha': 20}
-0.04377886854033632


In [83]:
lasso_regressor.predict(data)

array([43.40213806])

In [84]:
from sklearn.neural_network import MLPRegressor

In [42]:
from sklearn.svm import SVR
regr = SVR()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,50,60,70,80,90,100,200,300,400,500,600,700,800,900,1000,5000,10e+10]}
RF=GridSearchCV(regr,parameters,scoring='r2',cv=5)


In [46]:
regr.fit(X_train,y_train)


SVR()

In [44]:
regr.predict(data)

array([36.10033662])

In [102]:
from sklearn.neighbors import KNeighborsRegressor
Knn = KNeighborsRegressor()
Knn.fit(X_train,y_train)

KNeighborsRegressor()

In [103]:
Knn.predict(data)

array([34.])

GaussianProcessRegressor()

array([0.])

In [110]:
from sklearn.kernel_ridge import KernelRidge

In [ ]:
KernelRidge().fit(X_train,y_train)

In [ ]:
KernelRidge().predict(data)